config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :customers do
    resources :orders
    resources :subscriptions
    resources :messages
    resources :marketings
  end

  resources :orders do
    member do
      get :new_subscription
    end
  end

  resources :subscriptions
  resources :messages
  resources :users
  resources :marketings

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_and_belongs_to_many :marketings

  has_many :orders
  has_many :subscriptions
  has_many :messages

  accepts_nested_attributes_for :orders, reject_if: :all_blank

  def name
    [first_name, infix, last_name].compact.join(' ')
  end
end

app/models/marketing.rb
class Marketing < ActiveRecord::Base
  has_and_belongs_to_many :customers
  has_many :subscriptions
  has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :customer
  belongs_to :subscription
  belongs_to :marketing
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :customer
  has_many :subscriptions

  LENS_TYPES = [
    MONOFOCAL  = 'mono',
    MULTIFOCAL = 'multi',
    VARIFOCAL  = 'vari'
  ]

  REPLACEMENT_TYPES = [
    BI_WEEKLY = 'bi_weekly',
    MONTHLY   = 'monthly',
    DAILY     = 'daily'
  ]

  def end_date
    date + 6.months
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :customer
  belongs_to :order
end

app/models/text.rb
class Text < ActiveRecord::Base
  TYPES = [
    EMAIL = 'email',
    SMS   = 'sms'
  ]
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
    # @order    = @customer.orders.new
  end

  def create
    @customer = Customer.new(customer_params(params))
    if @customer.save!
      redirect_to @customer
    else
      render "new"
    end
  end

  def edit

  end

  def customer_params(params)
    params
      .require(:customer)
      .permit(
        :first_name,
        :infix,
        :last_name,
        :date_of_birth,
        :number,
        :phone,
        :email
      )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index

  end
end

app/controllers/marketings_controller.rb
class MarketingsController < ApplicationController
  def index

  end

  def show

  end

  def new

  end

  def create

  end

  def edit

  end

  def update

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def show
    @message = Message.find(params[:id])
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params(params))
    if @message.save!
      redirect_to @message
    else
      render 'new'
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.joins(:customer).all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @customer = Customer.find(params[:customer_id]) || nil
    @order = Order.new

    @lens_types = Order::LENS_TYPES.map do |type|
      {type => t(type, scope: 'activerecord.models.order.attributes.lens_types')}
    end

    @replacement_types = Order::REPLACEMENT_TYPES.map do |type|
      {type => t(type, scope: 'activerecord.models.order.attributes.replacement_types')}
    end
  end

  def new_subscription
    @order = Order.find(params[:id])

    @order.subscriptions.new(end_date: @order.end_date).save!

    flash[:success] = 'Nieuw abonnement aangemaakt'
    redirect_to @order
  end

  def create
    @order = Order.new(order_params(params))
    if @order.save!
      redirect_to @order
    else
      render 'new'
    end
  end

  def edit

  end

  def update

  end

  def order_params(params)
    params.require(:order).permit(:date, :number, :customer_id, :lens_type, :replacement_type)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def index
    @subscriptions = Subscription.includes(order: :customer).all
  end

  def show
    @subscritpion.find(params[:id])
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def index
    @texts = Text.all
  end

  def show
    @text = Text.find(params[:id])
  end

  def new
    @text = Text.new
  end

  def create
    @text = Text.new(text_params(params))
    if @text.save!
      redirect_to @text
    else
      render 'new'
    end
  end

  def edit
    @text = Text.find(params[:id])
  end

  def update
    @text = Text.find(params[:id])

    if @text.assign_attributes!(text_params(params))
      redirect_to @text
    else
      render 'edit'
    end
  end

  def text_params(params)
    params.require(:text).permit(:subject, :type, :body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # include Devise
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/index.html.slim
== content_for :title do
  | Klantenbeheer

.col-md-12
  .panel.panel-default
    .panel-heading= Customer.model_name.human.pluralize
    .panel-body
      = link_to 'Nieuwe klant', new_customer_path, {class: 'btn btn-primary pull-right'}
    table.table.table-striped.table-bordered
      thead
        th Naam
        th Geboortedatum
        th Klantnummer

      tbody
        - @customers.each do |customer|
          tr
            td = link_to customer.name, customer_path(customer)
            td = l(customer.date_of_birth, format: :long)
            td = customer.number

app/views/customers/new.html.slim
== content_for :title do
  ' Nieuwe Klant

.col-md-12
  .panel.panel-default
    .panel-heading = Customer.model_name.human
    .panel-body
      = form_for @customer, url: {action: 'create'} do |f|
        .row
          .col-md-12
            .col-md-6
              h2 Klant
              .form-group
                = f.label :first_name
                = f.text_field :first_name, class: 'form-control'
              .form-group
                = f.label :infix
                = f.text_field :infix, class: 'form-control'
              .form-group
                = f.label :last_name
                = f.text_field :last_name, class: 'form-control'
              .form-group
                = f.label :date_of_birth
                = f.date_field :date_of_birth, class: 'form-control'
              .form-group
                = f.label :number
                = f.text_field :number, class: 'form-control'
              .form-group
                = f.label :phone
                = f.text_field :phone, class: 'form-control'
              .form-group
                = f.label :email
                = f.text_field :email, class: 'form-control'
            /- f.fields_for :orders, @order do |of|
            /  .col-md-6
            /    h2 Bestelling
            /    .form-group
            /      = of.label :number
            /      = of.text_field :number, class: 'form-control'
            /    .form-group
            /      = of.label :date
            /      = of.date_field :date, value: Date.today, class: 'form-control'
            /    .form-group
            /      = of.label :lens_type
            /      = of.select :lens_type, Order::LENS_TYPES, {},
            /        class: 'form-control'
            /    .form-group
            /      = of.label :replacement_type
            /      = of.select :replacement_type, Order::REPLACEMENT_TYPES, {},
            /        class: 'form-control'
        .row
          .col-md-12
            .form-group
              = f.submit class: 'btn btn-primary'

app/views/customers/show.html.slim
== content_for :title do
  = @customer.name

.row
  .col-md-12
    /= link_to 'Nieuw abonnement', new_customer_subscription_path(@customer),
      {class: 'btn btn-success pull-right'}
    = link_to 'Nieuwe order', new_customer_order_path(@customer),
      {class: 'btn btn-primary pull-right'}
.row
  .col-md-4
    .panel.panel-default
      .panel-heading = Customer.model_name.human
      .panel-body
        dl.dl-horizontal
          dt= Customer.human_attribute_name(:first_name)
          dd= @customer.first_name
          dt= Customer.human_attribute_name(:infix)
          dd= @customer.infix
          dt= Customer.human_attribute_name(:last_name)
          dd= @customer.last_name
          dt= Customer.human_attribute_name(:date_of_birth)
          dd= l(@customer.date_of_birth, format: :long)
          dt= Customer.human_attribute_name(:number)
          dd= @customer.number
          dt= Customer.human_attribute_name(:phone)
          dd= @customer.phone
          dt= Customer.human_attribute_name(:email)
          dd= @customer.email

  .col-md-8
    .panel.panel-default
      .panel-heading = Order.model_name.human.pluralize
      table.table.table-striped.table-bordered
        thead
          th Ordernummer
          th Vervangingssysteem
          th Type lenzen
          th Datum
          th Einddatum
        tbody
          - @customer.orders.each do |order|
            tr
              td= link_to order.id, order_path(order)
              td= order.replacement_type
              td= order.lens_type
              td= l(order.date, format: :long)
              td= l(order.end_date, format: :long)
    .panel.panel-default
      .panel-heading = Subscription.model_name.human.pluralize
      table.table.table-striped.table-bordered
        thead
          th Ordernummer
          th SMS-frequentie
          th Eind datum
          th Type lenzen
        tbody
          - @customer.orders.flat_map(&:subscriptions).each do |subscription|
            tr
              td= subscription.order.number
              td= subscription.order.replacement_type
              td= l(subscription.end_date, format: :long)
              td= subscription.order.lens_type

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for(:title)
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  body
    .navbar.navbar-default.navbar-static-top
      .container
        button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
          span.icon-bar
          span.icon-bar
          span.icon-bar
        a.navbar-brand href="#" Broers optiek en optometrie
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li= link_to 'Klanten', customers_path
            li= link_to 'Abonnementen', subscriptions_path
            li= link_to 'Berichten', messages_path

    .container
      .row
        .col-lg-12
          = yield

app/views/orders/index.html.slim
== content_for :title do
  | Bestellingen

.col-md-12
  .panel.panel-default
    .panel-heading= Order.model_name.human.pluralize
    .panel-body
      = link_to 'Nieuwe Bestelling', new_order_path, {class: 'btn btn-primary pull-right'}
    table.table.table-striped.table-bordered
      thead
        th Ordernummer
        th Naam
        th Geboortedatum
        th Klantnummer
        th Vervangingssysteem
        th Type lenzen
        th Datum

      tbody
        - @orders.each do |order|
          tr
            td = link_to order.number, order_path(order)
            td = link_to order.customer.name, customer_path(order.customer)
            td = l(order.customer.date_of_birth, format: :long)
            td = order.customer.number
            td = order.replacement_type
            td = order.lens_type
            td = l(order.date, format: :long)

app/views/orders/new.html.slim
== content_for :title do
  ' Nieuwe bestelling

.col-md-12
  .panel.panel-default
    .panel-heading
      - if @customer
        = t('.new_order_for', customer: @customer.name)
      - else
        = t('.new_order')

    .panel-body
      = form_for @order, url: {action: 'create'} do |f|
        = f.hidden_field :customer_id, value: @customer.id
        .form-group
          = f.label :number
          = f.text_field :number, class: 'form-control'
        .form-group
          = f.label :date
          = f.date_field :date, value: Date.today, class: 'form-control'
        .form-group
          = f.label :lens_type
          = f.select :lens_type, Order::LENS_TYPES, {}, class: 'form-control'
        .form-group
          = f.label :replacement_type
          = f.select :replacement_type, Order::REPLACEMENT_TYPES, {}, class: 'form-control'
        .form-group
          = f.submit class: 'btn btn-primary'

app/views/orders/show.html.slim
== content_for :title do
  = @order.number

.row
  .col-md-12
    = link_to 'Nieuw abonnement', new_subscription_order_path(@order),
      {class: 'btn btn-primary pull-right', data: {confirm: 'Nieuw abonnement aanmaken?' }}
.row
  .col-md-4
    .panel.panel-default
      .panel-heading = Order.model_name.human
      .panel-body
        h4 Bestelling
        dl.dl-horizontal
          dt= Order.human_attribute_name(:number)
          dd= @order.number
          dt= Order.human_attribute_name(:date)
          dd= l(@order.date, format: :long)
          dt= t('.end_date')
          dd= l(@order.end_date, format: :long)
          dt= Order.human_attribute_name(:lens_type)
          dd= @order.lens_type
          dt= Order.human_attribute_name(:replacement_type)
          dd= @order.replacement_type
        h4 Klant
        dl.dl-horizontal
          dt= Customer.human_attribute_name(:first_name)
          dd= @order.customer.first_name
          dt= Customer.human_attribute_name(:infix)
          dd= @order.customer.infix
          dt= Customer.human_attribute_name(:last_name)
          dd= @order.customer.last_name
          dt= Customer.human_attribute_name(:date_of_birth)
          dd= l(@order.customer.date_of_birth, format: :long)
          dt= Customer.human_attribute_name(:number)
          dd= @order.customer.number
  .col-md-8
    .panel.panel-default
      .panel-heading= Subscription.model_name.human.pluralize
      table.table.table-striped.table-borderd
        thead
          th Einddatum
        tbody
          - @order.subscriptions.each do |subscription|
            tr
              td= l(subscription.end_date, format: :long)

app/views/subscriptions/index.html.slim
== content_for :title do
  | Abonnementen

.col-md-12
  .panel.panel-default
    .panel-heading= Subscription.model_name.human.pluralize
    table.table.table-striped.table-bordered
      thead
        th Klant naam
        th Geboortedatum
        th Klantnummer
        th Telefoon nummer
        th Email adres
        th Ordernummer
        th Lens type
        th Vervangingssysteem
        th Eind datum
      tbody
        - @subscriptions.each do |subscription|
          tr
            td = link_to subscription.order.customer.name, customer_path(subscription.order.customer)
            td = l(subscription.order.customer.date_of_birth, format: :long)
            td = subscription.order.customer.number
            td = subscription.order.customer.phone
            td = subscription.order.customer.email
            td = subscription.order.number
            td = subscription.order.lens_type
            td = subscription.order.replacement_type
            td = subscription.order.end_date

app/views/subscriptions/new.html.slim
== content_for :title do
  ' Nieuw abonnement

.col-md-12
  .panel.panel-default
    .panel-heading
      = t('.new_subscription_for', customer: @order.customer, @order.number)

    .panel-body
      = form_for @subscription, url: {action: 'create'} do |f|
        = f.hidden_field :customer_id, value: @order.id
        = f.hidden_field :order_id, value: @order.id

      .form-group
        = f.submit class: 'btn btn-primary'

app/views/subscriptions/show.html.slim
== content_for :title do
  = "Abonnement voor #{@subscription.order.customer.name}"

.row
  .col-md-4
    .panel.panel-default
      .panel-heading= Customer.model_name.human
      table.table.table-striped.table-bordered
        thead
          th= Customer.human_attribute_name(:first_name)
          th= Customer.human_attribute_name(:infix)
          th= Customer.human_attribute_name(:last_name)
          th= Customer.human_attribute_name(:date_of_birth)
          th= Customer.human_attribute_name(:number)
          th= Customer.human_attribute_name(:phone)
          th= Customer.human_attribute_name(:email)
        tbody
          tr
            td= @subscription.order.customer.first_name
            td= @subscription.order.customer.infix
            td= @subscription.order.customer.last_name
            td= l(@subscription.order.customer.date_of_birth, format: :long)
            td= @subscription.order.customer.number
            td= @subscription.order.customer.phone
            td= @subscription.order.customer.email

  .col-md-4
    .panel.panel-default
      .panel-heading= Order.model_name.human
      table.table.table-striped.table-borderd
        thead
          th= Order.human_attribute_name(:number)
          th= Order.human_attribute_name(:date)
          th= t('.end_date')
          th= Order.human_attribute_name(:lens_type)
          th= Order.human_attribute_name(:replacement_type)
        tbody
          tr
            td= @subscription.order.number
            td= l(@subscription.order.date, format: :long)
            td= l(@subscription.order.end_date, format: :long)
            td= @subscription.order.lens_type
            td= @subscription.order.replacement_type